a simple curl test

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -86,18 +86,19 @@ jobs:
 
       - name: Check if PV and PVC are Bound
         run: |
+          sleep 10
           kubectl get pvc
           kubectl get pv
 
-    #      PV_STATUS=$(kubectl get pv sqlite-pv -o jsonpath='{.status.phase}')
-    #      PVC_STATUS=$(kubectl get pvc sqlite-pvc -o jsonpath='{.status.phase}')
+          PV_STATUS=$(kubectl get pv sqlite-pv -o jsonpath='{.status.phase}')
+          PVC_STATUS=$(kubectl get pvc sqlite-pvc -o jsonpath='{.status.phase}')
 
-    #     if [ "$PV_STATUS" == "Bound" ] && [ "$PVC_STATUS" == "Bound" ]; then
-    #        echo "PV and PVC are bound!"
-    #      else
-    #        echo "PV or PVC is not bound."
-    #        exit 1
-    #      fi
+           if [ "$PV_STATUS" == "Bound" ] && [ "$PVC_STATUS" == "Bound" ]; then
+            echo "PV and PVC are bound!"
+          else
+            echo "PV or PVC is not bound."
+            exit 1
+          fi
 
       - name: Wait for Pods to be Ready
         run: |
@@ -106,21 +107,33 @@ jobs:
       - name: Test Deployment
         run: |
           # Get the Minikube IP
-          MINIKUBE_IP=$(minikube ip)
-          echo "Minikube IP: $MINIKUBE_IP"
+            MINIKUBE_IP=$(minikube ip)
+            echo "Minikube IP: $MINIKUBE_IP"
       
           # Get the NodePort assigned to the service
-          NODE_PORT=$(kubectl get svc flask-api-service -o jsonpath='{.spec.ports[0].nodePort}')
-          echo "NodePort: $NODE_PORT"
+            NODE_PORT=$(kubectl get svc flask-api-service -o jsonpath='{.spec.ports[0].nodePort}')
+            echo "NodePort: $NODE_PORT"
+      
+          # Test if the service is accessible using curl 
+          # Set the expected URL
+            expected_url="http://$MINIKUBE_IP:NODE_PORT"
 
-          kubectl get pods
-      
-          # Test if the service is accessible using curl (with GET method)
-          curl_result=$(curl -s -o /dev/null -w "%{http_code}" -X GET http://127.0.0.1:$NODE_PORT/api/users)
-      
-          if [ $curl_result -eq 200 ]; then
-            echo "Curl test successful!"
-          else
-            echo "Curl test failed with status code: $curl_result"
+          # Use curl to get the content of the URL
+            actual_output=$(curl -s "$expected_url")
+
+          # Set the expected content
+            expected_content="<!doctype html>
+            <html lang=en>
+            <title>404 Not Found</title>
+            <h1>Not Found</h1>
+            <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>"
+
+          # Compare the actual output with the expected content
+            if [ "$actual_output" = "$expected_content" ]; then
+            echo "Test passed! The content matches the expected output."
+            else
+            echo "Test failed! The content does not match the expected output."
+            echo "Actual output:"
+            echo "$actual_output"
             exit 1
-          fi
+            fi
